"""Agent adapter bundle generation for Codex/Copilot/OpenCode (M10_ADAPTERS).

This module renders and writes static file bundles that tell an external
coding agent (Codex, Copilot, or OpenCode) how to use the DMC MCP server. It
is deliberately a *file generator*, not a runtime integration: DMC does not
talk to Codex/Copilot/OpenCode processes directly, it only writes the
``AGENTS.md`` / instructions / config-template / skill files that those tools
already know how to read.

Design rules (see ``modules/M10_ADAPTERS.md`` and ``docs/TOOL_POLICY.md``):

* Output is files/instructions/config templates only, never a custom
  integration runtime.
* Generated protocol files (``AGENTS.md``, Copilot instructions, OpenCode
  ``AGENTS.md``) contain **protocol only** — no dynamic project facts (no
  paths, no timestamps, no repo-specific state) are ever embedded, matching
  the same "protocol vs. state" split this repository's own
  :doc:`/AGENTS.md` follows.
* Every adapter instructs the agent to call the DMC MCP tools
  (``dmc_plan_task``/``dmc_get_briefing`` at task start, ``dmc_precheck``
  before risky actions, ``dmc_record_event`` after meaningful actions,
  ``dmc_commit_state`` at checkpoints, ``dmc_distill_session`` at session end)
  and to never directly mutate accepted skills.

Public API
----------

``render_codex_bundle(project_root) -> dict[str, str]``
    Relative path -> file content for the Codex bundle.
``render_copilot_bundle(project_root) -> dict[str, str]``
    Relative path -> file content for the Copilot bundle.
``render_opencode_bundle(project_root) -> dict[str, str]``
    Relative path -> file content for the OpenCode bundle.
``export_agent_bundle(target, out_dir, *, project_root=None, store=None) -> list[Path]``
    Render the bundle for ``target`` and write it under the required
    ``out_dir``, returning the list of written paths. ``out_dir`` is never
    defaulted to the project root: a bundle export must not silently
    overwrite a caller's own ``AGENTS.md`` or other root files.
``default_out_dir(project_root, target) -> Path``
    The staging directory CLI/MCP callers should use when the user did not
    give an explicit output directory: ``<project_root>/.dmc/adapters/generated/<target>``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

__all__ = [
    "AdapterTarget",
    "VALID_TARGETS",
    "render_codex_bundle",
    "render_copilot_bundle",
    "render_opencode_bundle",
    "export_agent_bundle",
    "default_out_dir",
]

AdapterTarget = Literal["codex", "copilot", "opencode"]

#: The three supported adapter targets (module card scope).
VALID_TARGETS: tuple[str, ...] = ("codex", "copilot", "opencode")


# ---------------------------------------------------------------------------
# Shared protocol text (identical obligations, reworded per surface)
# ---------------------------------------------------------------------------

_PROTOCOL_STEPS = """\
1. At the start of a task, call `dmc_plan_task` and/or `dmc_get_briefing` to
   obtain a PlanGraph and a local briefing before making any changes.
2. Use Serena, GitHub, Sourcegraph, or Basic Memory MCP servers (if
   configured) for repo symbols/references, issues/PRs/commits, and
   cross-repo search or Markdown notes. DMC does not reimplement these.
3. Call `dmc_precheck` before any risky edit, test run, or benchmark.
4. Call `dmc_record_event` after every meaningful action, failure, or result.
5. Call `dmc_commit_state` at each checkpoint.
6. Call `dmc_distill_session` at the end of the session.
7. Never directly mutate accepted skills. Propose changes with
   `dmc_propose_skill_update` and let a human or review step accept them.\
"""

_TOOL_LIST = (
    "dmc_plan_task, dmc_render_graph, dmc_get_briefing, dmc_search, "
    "dmc_precheck, dmc_record_event, dmc_commit_state, dmc_distill_session, "
    "dmc_propose_skill_update, dmc_export_agent_bundle"
)


def _agents_md(surface: str) -> str:
    """Protocol-only ``AGENTS.md`` body shared by Codex and OpenCode."""
    return f"""# AGENTS.md — Dev Memory Compiler ({surface} adapter)

This file is generated by DMC's `M10_ADAPTERS` bundle exporter. It contains
**protocol only**; it must never be edited to record dynamic project state.

## DMC integration protocol

Any agent operating in this repository must follow the Dev Memory Compiler
(DMC) protocol below. DMC is a local-first memory/context sidecar; it does
not replace this agent's own execution loop.

{_PROTOCOL_STEPS}

## Available DMC MCP tools

{_TOOL_LIST}

## Notes

* DMC is a sidecar, not a harness: this agent remains in control of planning
  and execution.
* Regenerate this file with DMC's adapter exporter rather than editing it by
  hand; hand edits will be overwritten on the next export.
"""


def _codex_config_toml_template() -> str:
    return """\
# DMC MCP server registration template for Codex.
#
# This is a template, not a live config: copy the relevant section into your
# Codex configuration (e.g. `.codex/config.toml`) and adjust the command/args
# for your environment before use.

[mcp_servers.dmc]
command = "uv"
args = ["run", "dmc", "serve", "--root", "."]
# Adjust the "--root" value to the DMC project root if this config is not
# colocated with the DMC project (`dmc serve --root <path>`).
"""


def _copilot_instructions_md() -> str:
    return f"""# Copilot instructions — Dev Memory Compiler adapter

This file is generated by DMC's `M10_ADAPTERS` bundle exporter. It contains
**protocol only**; it must never be edited to record dynamic project state.

## DMC integration protocol

{_PROTOCOL_STEPS}

## Available DMC MCP tools

{_TOOL_LIST}

Never directly mutate accepted skills; propose changes with
`dmc_propose_skill_update` instead.
"""


def _skill_md(name: str, description: str, body: str) -> str:
    return f"""---
name: {name}
description: {description}
---

{body}
"""


def _dmc_start_task_skill_body() -> str:
    return f"""# Start a DMC-aware task

Use this skill whenever a new task begins in a repository that has DMC
configured.

{_PROTOCOL_STEPS}
"""


def _opencode_jsonc_template() -> str:
    return """\
{
  // DMC MCP server registration template for OpenCode.
  //
  // This is a template, not a live config: copy the relevant section into
  // your `opencode.jsonc` and adjust the command/args for your environment.
  "mcp": {
    "dmc": {
      "type": "local",
      "command": ["uv", "run", "dmc", "serve"],
      "enabled": true
    }
  }
}
"""


def _opencode_agent_md() -> str:
    return f"""---
description: DMC-aware coding agent that plans, prechecks, records, and distills through the DMC MCP server.
---

# DMC agent

{_PROTOCOL_STEPS}

## Available DMC MCP tools

{_TOOL_LIST}
"""


def _adapter_readme(target: str, files: list[str]) -> str:
    file_list = "\n".join(f"- `{f}`" for f in files)
    return f"""# DMC {target} adapter bundle

Generated by DMC's `M10_ADAPTERS` bundle exporter (`export_agent_bundle`).

## Files in this bundle

{file_list}

## How to wire it up

1. Review the generated files above before committing them.
2. Register the DMC MCP server using the `.template` config file for this
   surface (adjust the command/args for your environment).
3. Start a coding session; the agent should now follow the DMC protocol
   described in the generated instructions file.

This bundle contains protocol only. It carries no dynamic project state and
is safe to regenerate at any time.
"""


# ---------------------------------------------------------------------------
# Public render functions
# ---------------------------------------------------------------------------


def render_codex_bundle(project_root: str | Path) -> dict[str, str]:
    """Render the Codex adapter bundle: relative path -> file content.

    ``project_root`` is accepted for API symmetry with the other renderers
    and future extension, but is never embedded in generated content (no
    dynamic project facts in protocol files).
    """
    Path(project_root)  # validated for symmetry; content stays static
    files = {
        "AGENTS.md": _agents_md("Codex"),
        ".codex/config.toml.template": _codex_config_toml_template(),
    }
    files[".dmc/adapters/codex/README.md"] = _adapter_readme(
        "Codex", sorted(files.keys())
    )
    return files


def render_copilot_bundle(project_root: str | Path) -> dict[str, str]:
    """Render the Copilot adapter bundle: relative path -> file content."""
    Path(project_root)
    files = {
        ".github/copilot-instructions.md": _copilot_instructions_md(),
        ".github/skills/dmc-start-task/SKILL.md": _skill_md(
            name="dmc-start-task",
            description=(
                "Start a task in a DMC-configured repository: call "
                "dmc_plan_task/dmc_get_briefing first, precheck risky "
                "actions, record events, and distill at session end."
            ),
            body=_dmc_start_task_skill_body(),
        ),
    }
    files[".dmc/adapters/copilot/README.md"] = _adapter_readme(
        "Copilot", sorted(files.keys())
    )
    return files


def render_opencode_bundle(project_root: str | Path) -> dict[str, str]:
    """Render the OpenCode adapter bundle: relative path -> file content."""
    Path(project_root)
    files = {
        "AGENTS.md": _agents_md("OpenCode"),
        "opencode.jsonc.template": _opencode_jsonc_template(),
        ".dmc/adapters/opencode/agents/dmc-agent.md": _opencode_agent_md(),
        ".dmc/adapters/opencode/skills/dmc-start-task/SKILL.md": _skill_md(
            name="dmc-start-task",
            description=(
                "Start a task in a DMC-configured repository: call "
                "dmc_plan_task/dmc_get_briefing first, precheck risky "
                "actions, record events, and distill at session end."
            ),
            body=_dmc_start_task_skill_body(),
        ),
    }
    files[".dmc/adapters/opencode/README.md"] = _adapter_readme(
        "OpenCode", sorted(files.keys())
    )
    return files


_RENDERERS = {
    "codex": render_codex_bundle,
    "copilot": render_copilot_bundle,
    "opencode": render_opencode_bundle,
}


# ---------------------------------------------------------------------------
# Export (write bundle to disk)
# ---------------------------------------------------------------------------


def default_out_dir(project_root: str | Path, target: str) -> Path:
    """Default staging directory for a bundle when no explicit out_dir is given.

    This is **never** the project root itself: CLI/MCP callers use this when
    the user did not pass an explicit output directory, so that an adapter
    export can never silently overwrite a caller's own ``AGENTS.md`` or other
    root files.
    """
    return Path(project_root) / ".dmc" / "adapters" / "generated" / str(target)


def export_agent_bundle(
    target: AdapterTarget,
    out_dir: str | Path,
    *,
    project_root: str | Path | None = None,
    store: object | None = None,
) -> list[Path]:
    """Render and write the ``target`` adapter bundle, returning written paths.

    Parameters
    ----------
    target:
        One of ``"codex"``, ``"copilot"``, ``"opencode"``.
    out_dir:
        Directory the bundle is written under. **Required** — this function
        never guesses an output directory and never defaults to the project
        root, so it can never silently overwrite a caller's own ``AGENTS.md``
        or other root files. Callers with no explicit user-supplied output
        directory should pass :func:`default_out_dir` instead.
    project_root:
        Optional explicit project root passed through to the bundle
        renderers. Takes precedence over ``store.root``.
    store:
        Optional object exposing a ``.root`` attribute (e.g. a
        :class:`dmc.store.DMCStore`), used to resolve the project root when
        ``project_root`` is not given directly. Only ``.root`` is read; no
        other store behavior is used, keeping this a pure file generator.
    """
    if target not in _RENDERERS:
        raise ValueError(
            f"unknown adapter target {target!r}; expected one of {VALID_TARGETS}"
        )
    if out_dir is None:
        raise ValueError(
            "out_dir is required; refusing to guess an output directory "
            "(use default_out_dir(project_root, target) for a safe default)"
        )

    if project_root is not None:
        root = Path(project_root)
    elif store is not None and hasattr(store, "root"):
        root = Path(store.root)
    else:
        root = Path.cwd()

    files = _RENDERERS[target](root)

    out_dir = Path(out_dir)
    written: list[Path] = []
    for rel_path, content in files.items():
        dest = out_dir / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written.append(dest)
    return written
